/* Auto-generated from prisma/schema.prisma — do not edit by hand. */

import {
  Column,
  CreateDateColumn,
  Entity,
  JoinColumn,
  ManyToOne,
  OneToMany,
  PrimaryGeneratedColumn,
  UpdateDateColumn,
} from 'typeorm';
import { ColumnNumericTransformer } from './decimal.transformer';
import { PaymentMethod } from './enums';
import { Branch } from './branch.entity';
import { ExpenseCategory } from './expense-category.entity';
import { NutritionDay } from './nutrition-day.entity';
import { Payroll } from './payroll.entity';
import { PurchaseOrder } from './purchase-order.entity';
import { StockMovement } from './stock-movement.entity';
import { Supplier } from './supplier.entity';
import { Tenant } from './tenant.entity';

@Entity('Expense')
export class Expense {
  @PrimaryGeneratedColumn('uuid')
  id!: string;

  @Column({ type: 'uuid' })
  tenantId!: string;

  @ManyToOne(() => Tenant, (related) => related.expenses, { nullable: false })
  @JoinColumn({ name: 'tenantId' })
  tenant!: Tenant;

  @Column({ type: 'uuid' })
  branchId!: string;

  @ManyToOne(() => Branch, (related) => related.expenses, { nullable: false })
  @JoinColumn({ name: 'branchId' })
  branch!: Branch;

  @Column({ type: 'uuid' })
  categoryId!: string;

  @ManyToOne(() => ExpenseCategory, (related) => related.expenses, { nullable: false })
  @JoinColumn({ name: 'categoryId' })
  category!: ExpenseCategory;

  @Column({ type: 'decimal', precision: 18, scale: 2, transformer: ColumnNumericTransformer })
  amount!: number;

  @Column({ type: 'date' })
  date!: Date;

  @Column({ type: 'text', nullable: true })
  description!: string | null;

  @Column({ type: 'enum', enum: PaymentMethod, enumName: 'PaymentMethod', default: PaymentMethod.CASH })
  paymentMethod!: PaymentMethod;

  @Column({ type: 'text', nullable: true })
  attachmentUrl!: string | null;

  @Column({ type: 'uuid', nullable: true })
  supplierId!: string | null;

  @ManyToOne(() => Supplier, (related) => related.expenses, { nullable: true })
  @JoinColumn({ name: 'supplierId' })
  supplier!: Supplier | null;

  @Column({ type: 'uuid', nullable: true })
  purchaseOrderId!: string | null;

  @ManyToOne(() => PurchaseOrder, (related) => related.expenses, { nullable: true })
  @JoinColumn({ name: 'purchaseOrderId' })
  purchaseOrder!: PurchaseOrder | null;

  @Column({ type: 'uuid', nullable: true })
  payrollId!: string | null;

  @ManyToOne(() => Payroll, (related) => related.expenses, { nullable: true })
  @JoinColumn({ name: 'payrollId' })
  payroll!: Payroll | null;

  @Column({ type: 'boolean', default: false })
  isAutoGenerated!: boolean;

  @Column({ type: 'uuid', nullable: true })
  createdById!: string | null;

  @CreateDateColumn({ type: 'timestamp' })
  createdAt!: Date;

  @UpdateDateColumn({ type: 'timestamp' })
  updatedAt!: Date;

  @Column({ type: 'timestamp', nullable: true })
  deletedAt!: Date | null;

  @OneToMany(() => NutritionDay, (related) => related.expense)
  nutritionDays!: NutritionDay[];

  @OneToMany(() => StockMovement, (related) => related.expense)
  stockMovements!: StockMovement[];
}
