/* Auto-generated from prisma/schema.prisma — do not edit by hand. */

import {
  Column,
  CreateDateColumn,
  Entity,
  JoinColumn,
  ManyToOne,
  PrimaryGeneratedColumn,
  UpdateDateColumn,
} from 'typeorm';
import { ColumnNumericTransformer } from './decimal.transformer';
import { PaymentMethod } from './enums';
import { Branch } from './branch.entity';
import { IncomeCategory } from './income-category.entity';
import { Payment } from './payment.entity';
import { Tenant } from './tenant.entity';

@Entity('Income')
export class Income {
  @PrimaryGeneratedColumn('uuid')
  id!: string;

  @Column({ type: 'uuid' })
  tenantId!: string;

  @ManyToOne(() => Tenant, (related) => related.incomes, { nullable: false })
  @JoinColumn({ name: 'tenantId' })
  tenant!: Tenant;

  @Column({ type: 'uuid' })
  branchId!: string;

  @ManyToOne(() => Branch, (related) => related.incomes, { nullable: false })
  @JoinColumn({ name: 'branchId' })
  branch!: Branch;

  @Column({ type: 'uuid' })
  categoryId!: string;

  @ManyToOne(() => IncomeCategory, (related) => related.incomes, { nullable: false })
  @JoinColumn({ name: 'categoryId' })
  category!: IncomeCategory;

  @Column({ type: 'decimal', precision: 18, scale: 2, transformer: ColumnNumericTransformer })
  amount!: number;

  @Column({ type: 'date' })
  date!: Date;

  @Column({ type: 'text', nullable: true })
  description!: string | null;

  @Column({ type: 'enum', enum: PaymentMethod, enumName: 'PaymentMethod', default: PaymentMethod.CASH })
  paymentMethod!: PaymentMethod;

  @Column({ type: 'uuid', nullable: true })
  paymentId!: string | null;

  @ManyToOne(() => Payment, (related) => related.incomes, { nullable: true })
  @JoinColumn({ name: 'paymentId' })
  payment!: Payment | null;

  @Column({ type: 'boolean', default: false })
  isAutoGenerated!: boolean;

  @Column({ type: 'uuid', nullable: true })
  createdById!: string | null;

  @CreateDateColumn({ type: 'timestamp' })
  createdAt!: Date;

  @UpdateDateColumn({ type: 'timestamp' })
  updatedAt!: Date;

  @Column({ type: 'timestamp', nullable: true })
  deletedAt!: Date | null;
}
